version: '3.8'
services:
  tar1090_mod:
    environment:
      - TZ=${TZ}
    container_name: tar1090_mod
    build:
      context: ./tar1090_mod
      dockerfile: Dockerfile
      args:
        LAT: ${LAT}
        LONG: ${LONG}
    image: tar1090_mod:latest
    ports: 
      - 8078:80
    tmpfs:
      - /run:exec,size=64M
      - /var/log
    volumes:
      - /opt/adsb/tar1090/globe_history:/var/globe_history
      - /opt/adsb/tar1090/timelapse1090:/var/timelapse1090
      - /opt/adsb/tar1090/graphs1090:/var/lib/collectd
      - /proc/diskstats:/proc/diskstats:ro
      - /run/readsb:/run/readsb
    command: /bin/sh -c "mv /tmp/receiver.json /run/readsb/receiver.json && tail -f /dev/null"
    networks:
      drone_net:
        ipv4_address: 172.19.0.10
  
  sniffle:
    environment:
      - ${USB_DEVICE}:${USB_DEVICE}
    container_name: sniffle
    build:
      context: ./sniffle
      dockerfile: Dockerfile
    image: sniffle:latest
    ports:
      - 4222:4222
    device_cgroup_rules:
      - 'c 189:* rwm'
    tty: true
    devices: 
      - ${USB_DEVICE}:${USB_DEVICE}
    entrypoint: ["python3", "/src/Sniffle/python_cli/sniff_receiver.py", "-s", "${USB_DEVICE}", "-l", "-e", "-z", "--zmqsetting", "172.19.0.11:4222", "-v"]
    networks:
      drone_net:
        ipv4_address: 172.19.0.11

  zmqDecoder:
    container_name: zmqDecoder
    build:
      context: ./DroneID
      dockerfile: Dockerfile
    image: droneid:latest
    ports:
      - 4224:4224
    entrypoint: ["python3", "/src/DroneID/zmq_decoder.py", "-z", "--zmqclients", "172.19.0.11:4222", "--zmqsetting", "172.19.0.12:4224", "-v"]
    networks:
      drone_net:
        ipv4_address: 172.19.0.12

  zmqToTar1090:
    container_name: zmqToTar1090
    build:
      context: ./zmqToTar1090
      dockerfile: Dockerfile
    image: zmqtotar1090:latest
    entrypoint: ["python3", "/src/zmqToTar1090/zmqToTar1090.py", "--zmq-host", "172.19.0.12", "--zmq-port", "4224", "-d"]
    volumes:
      - /run/readsb:/run/readsb
    networks:
      drone_net:
        ipv4_address: 172.19.0.13

networks:
  drone_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/24
          gateway: 172.19.0.5
